export const LOAD_FRONT_IMAGES = "LOAD_FRONT_IMAGES";
export const SET_FILTER_ROOMS = "SET_FILTER_ROOMS";
export const UNSET_FILTER_ROOMS = "UNSET_FILTER_ROOMS";
export const FILTER_ROOMS = "FILTER_ROOMS";
export const LOAD_FILTER = "LOAD_FILTER";
